# name: php-myadmin-and-mysql
# services:
#   db:
#     image: mysql:5.7
#     container_name: mysql5.7
#     restart: always
#     environment:
#       MYSQL_ROOT_PASSWORD: rootpassword
#       MYSQL_DATABASE: mydatabase
#       MYSQL_USER: myuser
#       MYSQL_PASSWORD: mypassword
#     ports:
#       - "3307:3306"
#     command: --default-authentication-plugin=mysql_native_password
#     volumes:
#       - ./mysql_data:/var/lib/mysql
#     networks:
#       - default
#   phpmyadmin:
#     image: phpmyadmin/phpmyadmin
#     container_name: phpmyadmin
#     restart: always
#     networks:
#       - default
#     environment:
#       PMA_ARBITRARY: 1
#       PMA_HOST: db
#       PMA_PORT: 3306
#       PMA_USER: myuser
#       PMA_PASSWORD: mypassword
#     ports:
#       - "9090:80"
#     depends_on:
#       - db
#   wordpress:
#     image: wordpress:latest
#     container_name: wordpress
#     restart: always
#     environment:
#       WORDPRESS_DB_HOST: db:3306
#       WORDPRESS_DB_USER: myuser
#       WORDPRESS_DB_PASSWORD: mypassword
#       WORDPRESS_DB_NAME: mydatabase
#     ports:
#       - "8081:80"
#     depends_on:
#       - db
# volumes:
#   mysql_data:
# networks:
#   default:
#     driver: bridge

services:
  wordpress:
    image: wordpress:latest
    container_name: wordpress
    restart: always
    depends_on:
      - db
    ports:
      - "8083:80"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress_password
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - default

  db:
    image: mysql:5.7
    container_name: wordpress_db
    restart: always
    ports:
      - "3308:3306"
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress_password
      MYSQL_ROOT_PASSWORD: root_password
    volumes:
      - db_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - default

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    depends_on:
      - db
    ports:
      - "8081:80"
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: wordpress
      PMA_PASSWORD: wordpress_password
      MYSQL_ROOT_PASSWORD: root_password
    networks:
      - default

  phpapp:
    build: .
    container_name: php-app
    restart: always
    depends_on:
      - db
    ports:
      - "8082:80"
    environment:
      MYSQL_HOST: db
      MYSQL_USER: root
      MYSQL_PASSWORD: root_password
      MYSQL_DB: wordpress
    networks:
      - default

volumes:
  wordpress_data:
  db_data:

networks:
  default:
    driver: bridge
