pipeline {
    agent any

    environment {
        IMAGE = 'ksk6699/php-app'
    }

    stages {
        stage('Checkout Code') {
            steps {
                checkout scm
            }
        }

    stage('Deploy') {
        steps {
            sh 'echo "Deploying the project..."'
            sshagent(credentials: ['smm-ssh']) {
                sh '''
                    ssh -o StrictHostKeyChecking=no ubuntu@54.66.234.101 "
                        sudo docker network create appnet 2>/dev/null || true

                        sudo docker inspect php-db > /dev/null 2>&1 || sudo docker run -d --name php-db \
                            --network appnet \
                            -e MYSQL_DATABASE=wordpress \
                            -e MYSQL_USER=wordpress \
                            -e MYSQL_PASSWORD=wordpress_password \
                            -e MYSQL_ROOT_PASSWORD=root_password \
                            mysql:5.7

                        sudo docker rm -f php-app || true
                        sudo docker run -d --name php-app \
                            --network appnet \
                            -e MYSQL_HOST=php-db \
                            -e MYSQL_USER=root \
                            -e MYSQL_PASSWORD=root_password \
                            -e MYSQL_DB=wordpress \
                            -p 9098:80 $IMAGE:$BUILD_NUMBER
                    "
                '''
            }
        }
    }

        stage('Push Image') {
            steps {
                sh 'echo "Push image to registry..."'
                withCredentials([usernamePassword(credentialsId: 'docker-hub-id',
                                                  usernameVariable: 'DOCKER_USERNAME',
                                                  passwordVariable: 'DOCKER_PASSWORD')]) {
                    sh 'echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin'
                    sh 'docker push $IMAGE:$BUILD_NUMBER'
                    sh 'docker logout'
                }
            }
        }

        stage('Deploy') {
            steps {
                sh 'echo "Deploying the project..."'
                sshagent(credentials: ['smm-ssh']) {
                    sh '''
                        ssh -o StrictHostKeyChecking=no ubuntu@54.66.234.101 "
                            sudo docker rm -f php-app || true
                            sudo docker run -d --name php-app -p 9098:80 $IMAGE:$BUILD_NUMBER
                        "
                    '''
                }
            }
        }
    }
}